-

diff --git a/.github/workflows/tests.yml b/.github/workflows/tests.yml
--- a/.github/workflows/tests.yml
+++ b/.github/workflows/tests.yml
@@ -46,17 +46,41 @@ jobs:
 
       - run: npm install
 
-      - name: Jest test with Coverage
+       name: jest test with results file
         continue-on-error: true
         working-directory: 'tests' 
-        run: npm run test --json --outputFile=/home/runner/work/room-card/room-card/jest-results.json
-
-      - name: Process jest results with default
-        if: always()
+        run: jest --json --outputFile=/home/runner/work/room-card/room-card/jest-results.json
+      
+      - name: Process jest results
+        id: process-jest
         uses: im-open/process-jest-test-results@v2.0.6
         with:
           github-token: ${{ secrets.GITHUB_TOKEN }}
-          results-file: '/home/runner/work/room-card/room-card/jest-results.json'
+          results-file: 'jest.json'
+          report-name: 'Jest Results'
+          create-status-check: true
+          create-pr-comment: false
+          update-comment-if-one-exists: false
+          ignore-test-failures: true
+          timezone: 'europe/amsterdam'
+
+      - name: Fail if there were errors in the jest tests
+        if: steps.process-jest.outputs.test-outcome == 'Failed'
+        run: |
+          echo "There were test failures."
+          exit 1
+
+      # - name: Jest test with Coverage
+      #   continue-on-error: true
+      #   working-directory: 'tests' 
+      #   run: npm run test --json --outputFile=/home/runner/work/room-card/room-card/jest-results.json
+
+      # - name: Process jest results with default
+      #   if: always()
+      #   uses: im-open/process-jest-test-results@v2.0.6
+      #   with:
+      #     github-token: ${{ secrets.GITHUB_TOKEN }}
+      #     results-file: '/home/runner/work/room-card/room-card/jest-results.json'
 
   # coverage:
   #   name: Coverage
